within ThermalAndPowerGridSystem;

package ThermalGrid
   extends Modelica.Icons.MaterialProperty;
   annotation (Documentation(info= "<html><head></head><body><h1><p><b><u>     
Thermal Grid Package</u>
</b></p></h1>
<h4>This package contains models of components and utilities capable of building thermo-fluid models. These can be used for annual simulation of small or large scenarios of thermal energy generation, distribution and consumption.  Examples of scenarios and controllers for the same are included.&nbsp;</h4><div><br></div>The package includes components to describe thermo-fluid flow. Stream connectors connect these components, hence eliminating the need for explicit mixing junctions and flow splitters. The library describes the flow of water, however, water can be easily replaced with other medium from the media package .<div><div><div><br></div><div><div><ul><li>In order to maintain the same ambient conditions for all componentss of a simulation scenario, <a href=\"modelica://ThermalAndPowerGridSystem.ThermalGrid.SystemSetup.AmbientConditions\">Ambient Conditions </a> is maintained as a record, changes of which will be reflected across all components of a scenario alike.<br><br></li><li>Two or more components can be connected together.<br><br></li><li>Models under <a href=\"modelica://ThermalAndPowerGridSystem.ThermalGrid.Components\">Components </a> &nbsp;may be used as single components for small or big scenarios. Models are <a href=\"modelica://ThermalAndPowerGridSystem.ThermalGrid.CompoundComponents\">CompoundComponents </a>  may be used as a collection of models for simultation of large scenarios.<br><br></li><li>These models are built of low complexity for the purpose of annual simulations of Thermal Grid Simulations.&nbsp;<br><br></li><li>Given the above assumptions and limitations,<span style=\"font-family: 'MS Shell Dlg 2'; font-size: 12px;\">there is no restriction how components can be connected together. The resulting simulation performance however often strongly depends on the model structure and modeling assumptions made. In particular the direct connection of fluid volumes generally results in high-index DAEs for the pressures. The direct connection of flow models generally results in systems of implicit nonlinear algebraic equations.</span></li></ul></div></div></div></div></body></html>"));
end ThermalGrid;
